"""Regenerate PNG colors and .map lookup tables from the 1.4.5.8 MapHelper snapshot.

Snapshot rows [id, option, lookup, r, g, b] come from decodeAssets' server
metadata tile_ids.generated.json / wall_ids.generated.json. Keep lookup values:
MapHelper uses one shared palette across tiles, walls, liquids and backgrounds.
Run python scripts/generate_color_data.py [--check].
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def array(name, values, kind='uint8_t', width=24):
    return f'static const {kind} {name}[{len(values)}] = {{\n' + ''.join(
        '  ' + ', '.join(map(str, values[i:i + width])) + ',\n'
        for i in range(0, len(values), width)) + '};\n'


def generate():
    p = json.loads((ROOT / 'data/map-palette-1458.json').read_text())
    header = ('/* Generated by scripts/generate_color_data.py; source: data/map-palette-1458.json. */\n'
              '#ifndef TERRA_COLOR_DATA_H\n#define TERRA_COLOR_DATA_H\n#include <stdint.h>\n'
              '#define TX_COLOR_MAX_IDS 1024\n#define TX_COLOR_MAX_VARIANTS 16\n'
              '#define TX_BAD_TILE_COUNT 6\n'
              'static const uint16_t TX_BAD_TILE_IDS[TX_BAD_TILE_COUNT] = {127,135,210,428,504,541};\n'
              '#define TX_BAD_WALL_COUNT 11\n'
              'static const uint16_t TX_BAD_WALL_IDS[TX_BAD_WALL_COUNT] = {0,21,88,89,90,91,92,93,168,241,318};\n')
    defaults = '/* Generated by scripts/generate_color_data.py; Terraria 1.4.5.8 MapHelper lookup. */\n'
    counts = {'TILE': p['tileCount'], 'WALL': p['wallCount']}
    last_wall = max(row[2] for row in p['walls'])
    constants = {'VERSION':33083, 'TILE_COUNT':p['tileCount'], 'WALL_COUNT':p['wallCount'],
                 'LIQUID_COUNT':4, 'SKY_GRADIENTS':256, 'DIRT_GRADIENTS':256, 'ROCK_GRADIENTS':256,
                 'MAX_WALL_ID':last_wall, 'MAX_LIQUID_ID':last_wall+4,
                 'DIRT_ID':last_wall+261, 'ROCK_ID':last_wall+517, 'HELL_ID':last_wall+773}
    for name, value in constants.items():
        defaults += f'static const uint32_t TX_MAP_{name}={value}u;\n'
    all_lookups = []
    for kind in ('TILE', 'WALL'):
        colors = [0] * (1024 * 16 * 4)
        types, lookups = [0] * counts[kind], [0] * counts[kind]
        for ident, option, lookup, r, g, b in p[kind.lower()+'s']:
            assert ident < counts[kind] and option < 16 and 0 < lookup < 65536
            colors[(ident*16+option)*4:(ident*16+option)*4+4] = [r,g,b,255]
            types[ident] = max(types[ident], option+1)
            if option == 0: lookups[ident] = lookup
            else: assert lookup == lookups[ident]+option
            all_lookups.append(lookup)
        header += array('TX_BUILTIN_'+kind+'_COLORS', colors, width=64)
        exists = [int(n != 1) for n in types] # .map stores counts only when !=1
        bits = [sum(exists[i+j] << j for j in range(min(8,len(exists)-i)))
                for i in range(0,len(exists),8)]
        defaults += array('TX_MAP_'+kind+'_OPTIONS', bits)
        defaults += array('TX_MAP_'+kind+'_EXISTS', exists)
        defaults += array('TX_MAP_'+kind+'_TYPE_COUNTS', types)
        defaults += array('TX_MAP_'+kind+'_ID_LIST', lookups, 'uint16_t')
    assert sorted(all_lookups) == list(range(1,last_wall+1))
    header += array('TX_PAINT_COLORS',p['paints']) + '#endif\n'
    return {'include/terra_color_data.h':header, 'src/terra_defaults.inc':defaults}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, text in generate().items():
        path = ROOT / name
        if args.check: assert path.read_text() == text, f'{name} is stale'
        else: path.write_text(text)
