"""Extract NPCID's legacy dictionary without requiring Terraria at build time."""

import argparse
import hashlib
import json
from pathlib import Path
import re


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=root.parent / "code/Terraria.ID/NPCID.cs")
    parser.add_argument("--output", type=Path, default=root / "src/terra_legacy_npc.c")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = args.source.read_bytes()
    source = data.decode("utf-8-sig")
    dictionary = source.split("LegacyNameToIdMap =", 1)[1].split("\n\t};", 1)[0]
    entries = re.findall(r'\{\s*("(?:[^"\\]|\\.)*")\s*,\s*(-?\d+)\s*\}', dictionary)
    if not entries or len(entries) != dictionary.count("{ "):
        raise ValueError("NPCID dictionary shape changed; inspect it before regenerating")
    names = [(json.loads(name), int(value)) for name, value in entries]
    if len(dict(names)) != len(names):
        raise ValueError("duplicate NPC legacy name")
    lines = [
        "/* Generated by scripts/generate_legacy_npc_names.py from NPCID.cs.",
        f" * Source SHA-256: {hashlib.sha256(data).hexdigest()}",
        " * Do not edit entries by hand. */",
        '#include "terra_legacy.h"',
        "extern int tx_streq_c(const char *, const char *);",
        "static const struct { const char *name; int16_t id; } npc_names[] = {",
    ]
    lines += [f"    {{{json.dumps(name, ensure_ascii=True)}, {value}}}," for name, value in names]
    lines += [
        "};",
        "int32_t tx_legacy_npc_id(const char *name) {",
        "    if (!name) return 0;",
        "    for (uint32_t i = 0; i < sizeof(npc_names) / sizeof(npc_names[0]); i++)",
        "        if (tx_streq_c(name, npc_names[i].name)) return npc_names[i].id;",
        "    return 0;",
        "}",
        "",
    ]
    output = "\n".join(lines)
    if args.check:
        if args.output.read_text(encoding="utf-8") != output:
            raise SystemExit("generated legacy NPC dictionary is out of date")
    else:
        args.output.write_text(output, encoding="utf-8", newline="\n")
    print(f"Verified {len(entries)} legacy NPC names")


if __name__ == "__main__":
    main()
