#!/usr/bin/env python3
"""Generate immutable native actuation flags from the source-derived catalog.

The catalog records its Terraria source commit. Extra WorldGen support flags
come directly from TileID.cs at the same checkout. No build-time download or
dependency on the companion application's runtime is introduced.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--catalog', required=True, type=Path)
    parser.add_argument('--tile-id', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args()
    catalog_bytes = args.catalog.read_bytes()
    catalog = json.loads(re.search(r'Object\.freeze\((\{.*\})\)', catalog_bytes.decode(), re.S)[1])
    if catalog['sourceCommit'] != '8255d34616c780af12079425ac92a0a7aed87d71':
        raise SystemExit('This generator requires the pinned reviewed Terraria source flags')
    source_bytes = args.tile_id.read_bytes()
    source_sha256 = hashlib.sha256(source_bytes).hexdigest()
    if source_sha256 != '9e766249c1a4ea56bc10dd1019a0502243be12177defc50c7febb6e4c1615807':
        raise SystemExit('TileID.cs does not match the pinned reviewed source; review the source and update its pin first')
    source = source_bytes.decode('utf-8-sig')
    def ids(name):
        expression = re.search(r'\b' + name + r'\s*=\s*Factory\.CreateBoolSet\(([^)]*)\)', source)[1]
        return [int(value) for value in re.findall(r'\b\d+\b', expression)]
    sets = [
        ('SOLID', catalog['tileSolid']),
        ('NOT_REALLY_SOLID', catalog['NotReallySolid']),
        ('PREVENTS_ACTUATION_UNDER', catalog['PreventsActuationUnder']),
        ('BOULDER', catalog['Boulders']),
        ('DEACTIVE_EXCLUDED', catalog['DeActiveExcluded']),
        ('TREE_TRUNK', ids('IsATreeTrunk')),
        ('PREVENTS_REMOVAL_UNDER', ids('PreventsTileRemovalIfOnTopOfIt')),
        ('CONTAINER', ids('BasicChest') + ids('BasicChestFake') + ids('BasicDresser') + [470, 475]),
    ]
    maximum = max(max(values) for _, values in sets)
    flags = [0] * (maximum + 1)
    for index, (_, values) in enumerate(sets):
        for value in values:
            flags[value] |= 1 << index
    lines = ['#ifndef TERRA_CIRCUIT_MATERIALS_H', '#define TERRA_CIRCUIT_MATERIALS_H', '#include <stdint.h>',
        '/* Generated by scripts/generate-circuit-materials.py.',
        ' * Terraria source: ' + catalog['sourceCommit'],
        ' * Catalog SHA-256: ' + hashlib.sha256(catalog_bytes).hexdigest(),
        ' * TileID.cs SHA-256: ' + source_sha256 + ' */']
    for index, (name, _) in enumerate(sets):
        lines.append('#define CX_MATERIAL_' + name + ' ' + str(1 << index) + 'u')
    lines.append('static const uint8_t cx_material_flags[' + str(len(flags)) + '] = {')
    for offset in range(0, len(flags), 24):
        lines.append('    ' + ','.join(str(value) for value in flags[offset:offset+24]) + ',')
    lines += ['};', 'static inline int cx_material_has(uint32_t type, uint32_t flag) {',
        '    return type < sizeof(cx_material_flags) && (cx_material_flags[type] & flag) != 0;', '}', '#endif', '']
    args.out.write_bytes('\n'.join(lines).encode('utf-8'))


if __name__ == '__main__':
    main()
