#ifndef TERRA_CIRCUIT_ANCHOR_PERMISSIONS_H
#define TERRA_CIRCUIT_ANCHOR_PERMISSIONS_H
/* Generated by scripts/generate-circuit-anchor-permissions.py.
 * TileObjectData.cs source 8255d34616c780af12079425ac92a0a7aed87d71.
 * SHA-256: 348b09f93e78a2e704a137fc39e871bb7da5e5ad89519e9f1c0a2705cc5cf345.
 * Per-side material predicates; saved-frame anchor geometry comes from the caller. */
#define CX_ANCHOR_SOLID_TILE 1u
#define CX_ANCHOR_SOLID_WITH_TOP 2u
#define CX_ANCHOR_TABLE 4u
#define CX_ANCHOR_SOLID_SIDE 8u
#define CX_ANCHOR_PLATFORM 16u
#define CX_ANCHOR_SOLID_BOTTOM 32u
#define CX_ANCHOR_PLATFORM_NON_HAMMERED 64u
#define CX_ANCHOR_PLANTER_BOX 128u
#define CX_ANCHOR_ALTERNATE_TILE 256u
#define CX_ANCHOR_TREE 512u
#define CX_ANCHOR_EMPTY_TILE 1024u
#define CX_ANCHOR_ALL_FLAT_HEIGHT 2048u
static const unsigned int cx_anchor_permissions[754] = {
    0u,0u,0u,11u,16777225u,0u,0u,0u,0u,0u,4097u,4097u,15u,4u,11u,11u,
    11u,11u,11u,0u,1u,11u,0u,0u,11u,0u,11u,1u,11u,4u,0u,0u,
    0u,4u,36864u,15u,11u,0u,0u,0u,0u,0u,626688u,0u,0u,0u,0u,0u,
    0u,4u,4u,0u,0u,0u,0u,36879u,0u,0u,0u,0u,0u,11u,0u,0u,
    0u,0u,0u,0u,0u,0u,0u,11u,0u,11u,11u,0u,0u,11u,15u,11u,
    0u,4194315u,257u,257u,257u,15u,11u,11u,11u,11u,11u,757760u,11u,11u,15u,36864u,
    11u,15u,15u,15u,15u,11u,11u,4u,11u,11u,11u,0u,0u,0u,11u,0u,
    0u,11u,11u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,15u,36864u,0u,
    11u,0u,0u,0u,15u,11u,11u,11u,16777225u,0u,15u,15u,0u,11u,15u,15u,
    0u,0u,0u,0u,0u,4097u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,
    0u,0u,0u,0u,0u,1216523u,0u,0u,0u,0u,0u,3u,15u,15u,4u,0u,
    0u,0u,4097u,0u,0u,0u,0u,0u,4097u,11u,11u,11u,0u,0u,0u,0u,
    0u,0u,0u,0u,0u,0u,0u,0u,0u,11u,0u,0u,0u,0u,0u,11u,
    0u,3u,11u,0u,11u,0u,0u,11u,11u,11u,11u,11u,11u,0u,0u,0u,
    0u,0u,0u,4199425u,11u,0u,0u,11u,0u,15u,0u,11u,15u,11u,15u,11u,
    0u,0u,0u,11u,11u,0u,0u,11u,0u,0u,0u,0u,0u,0u,1u,0u,
    0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,11u,626688u,626688u,
    0u,0u,0u,13u,13u,13u,13u,13u,13u,13u,15u,11u,0u,13u,13u,15u,
    15u,15u,15u,15u,15u,15u,15u,15u,13u,13u,13u,13u,11u,11u,11u,11u,
    11u,11u,11u,11u,11u,13u,13u,0u,0u,0u,0u,0u,15u,15u,15u,15u,
    11u,0u,0u,0u,15u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,15u,
    0u,11u,11u,13u,0u,0u,0u,0u,0u,0u,0u,0u,0u,11u,0u,0u,
    0u,0u,15u,15u,11u,0u,13u,13u,15u,13u,13u,13u,13u,0u,0u,0u,
    0u,0u,0u,0u,4u,4096u,4096u,4096u,15u,11u,11u,0u,0u,0u,0u,0u,
    0u,0u,0u,0u,4097u,4097u,15u,13u,13u,13u,13u,36879u,0u,0u,0u,0u,
    0u,0u,0u,0u,0u,11u,11u,0u,0u,0u,11u,15u,11u,13u,13u,0u,
    0u,0u,0u,256u,0u,0u,0u,0u,0u,36879u,0u,0u,11u,0u,0u,0u,
    0u,0u,0u,0u,0u,0u,0u,0u,0u,11u,24311599u,131083u,36864u,0u,0u,0u,
    0u,0u,0u,0u,11u,11u,36864u,11u,11u,15u,0u,0u,0u,4096u,4u,11u,
    11u,9342976u,11u,11u,11u,11u,11u,0u,0u,0u,0u,11u,7u,0u,0u,0u,
    11u,0u,0u,0u,15u,1u,11u,11u,11u,11u,15u,15u,0u,11u,7u,0u,
    0u,11u,0u,11u,0u,0u,0u,0u,0u,15u,11u,0u,0u,11u,36879u,36879u,
    0u,0u,0u,0u,0u,0u,0u,0u,7u,15u,15u,15u,15u,15u,15u,15u,
    0u,0u,11u,167936u,13u,13u,0u,0u,0u,0u,13u,0u,0u,0u,13u,15u,
    13u,11u,0u,11u,11u,0u,13u,13u,11u,13u,13u,13u,13u,0u,13u,13u,
    15u,0u,0u,0u,15u,15u,0u,11u,15u,15u,15u,0u,626688u,36879u,0u,0u,
    0u,0u,0u,5u,15u,626688u,13u,0u,0u,0u,0u,0u,0u,0u,1u,9342976u,
    9342976u,15u,15u,1u,0u,11u,15u,13u,13u,13u,13u,13u,13u,13u,13u,13u,
    13u,13u,13u,13u,13u,11u,11u,1u,0u,11u,0u,13u,15u,15u,15u,11u,
    11u,0u,0u,0u,0u,13u,1216779u,1216779u,13u,0u,0u,0u,0u,11u,0u,15u,
    13u,0u,11u,13u,13u,13u,4u,11u,11u,11u,11u,11u,15u,11u,15u,0u,
    11u,11u,11u,0u,626688u,0u,0u,11u,15u,15u,0u,0u,0u,0u,0u,0u,
    0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,
    0u,0u,0u,0u,0u,1216523u,1216523u,11u,0u,0u,1806336u,11u,9u,11u,15u,11u,
    11u,11u,11u,4u,0u,4096u,13u,15u,15u,15u,15u,15u,15u,0u,0u,0u,
    11u,11u,0u,1216779u,1216779u,11u,0u,0u,0u,0u,0u,0u,0u,11u,0u,0u,
    0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,0u,15u,
    15u,267u,
};
static unsigned cx_anchor_bottom_type(unsigned type) {
    return type < 754u ? cx_anchor_permissions[type] & 4095u : 0;
}
static unsigned cx_anchor_top_type(unsigned type) {
    return type < 754u ? (cx_anchor_permissions[type] >> 12) & 4095u : 0;
}
static int cx_anchor_flattens(unsigned type) {
    return type < 754u && (cx_anchor_permissions[type] & (1u << 24));
}
#endif
