#ifndef TERRA_CIRCUIT_ANCHOR_PERMISSIONS_H
#define TERRA_CIRCUIT_ANCHOR_PERMISSIONS_H
/* Generated by scripts/generate-circuit-anchor-permissions.py.
 * TileObjectData.cs source 8255d34616c780af12079425ac92a0a7aed87d71.
 * SHA-256: 348b09f93e78a2e704a137fc39e871bb7da5e5ad89519e9f1c0a2705cc5cf345.
 * Per-side material predicates; saved-frame anchor geometry comes from the caller. */
#define CX_ANCHOR_SOLID_TILE 1u
#define CX_ANCHOR_SOLID_WITH_TOP 2u
#define CX_ANCHOR_TABLE 4u
#define CX_ANCHOR_SOLID_SIDE 8u
#define CX_ANCHOR_PLATFORM 16u
#define CX_ANCHOR_SOLID_BOTTOM 32u
#define CX_ANCHOR_PLATFORM_NON_HAMMERED 64u
#define CX_ANCHOR_PLANTER_BOX 128u
#define CX_ANCHOR_ALTERNATE_TILE 256u
#define CX_ANCHOR_TREE 512u
#define CX_ANCHOR_EMPTY_TILE 1024u
#define CX_ANCHOR_ALL_FLAT_HEIGHT 2048u
static const unsigned int cx_anchor_masks[29] = {
    0u,1u,3u,4u,5u,7u,9u,11u,
    13u,15u,256u,257u,267u,4096u,4097u,36864u,
    36879u,131083u,167936u,626688u,757760u,1216523u,1216779u,1806336u,
    4194315u,4199425u,9342976u,16777225u,24311599u,
};
static const unsigned char cx_anchor_mask_index[754] = {
    0,0,0,7,27,0,0,0,0,0,14,14,9,3,7,7,7,7,7,0,1,7,0,0,7,0,7,1,7,3,0,0,
    0,3,15,9,7,0,0,0,0,0,19,0,0,0,0,0,0,3,3,0,0,0,0,16,0,0,0,0,0,7,0,0,
    0,0,0,0,0,0,0,7,0,7,7,0,0,7,9,7,0,24,11,11,11,9,7,7,7,7,7,20,7,7,9,15,
    7,9,9,9,9,7,7,3,7,7,7,0,0,0,7,0,0,7,7,0,0,0,0,0,0,0,0,0,0,9,15,0,
    7,0,0,0,9,7,7,7,27,0,9,9,0,7,9,9,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,21,0,0,0,0,0,2,9,9,3,0,0,0,14,0,0,0,0,0,14,7,7,7,0,0,0,0,
    0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,7,0,2,7,0,7,0,0,7,7,7,7,7,7,0,0,0,
    0,0,0,25,7,0,0,7,0,9,0,7,9,7,9,7,0,0,0,7,7,0,0,7,0,0,0,0,0,0,1,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,7,19,19,0,0,0,8,8,8,8,8,8,8,9,7,0,8,8,9,
    9,9,9,9,9,9,9,9,8,8,8,8,7,7,7,7,7,7,7,7,7,8,8,0,0,0,0,0,9,9,9,9,
    7,0,0,0,9,0,0,0,0,0,0,0,0,0,0,9,0,7,7,8,0,0,0,0,0,0,0,0,0,7,0,0,
    0,0,9,9,7,0,8,8,9,8,8,8,8,0,0,0,0,0,0,0,3,13,13,13,9,7,7,0,0,0,0,0,
    0,0,0,0,14,14,9,8,8,8,8,16,0,0,0,0,0,0,0,0,0,7,7,0,0,0,7,9,7,8,8,0,
    0,0,0,10,0,0,0,0,0,16,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,7,28,17,15,0,0,0,
    0,0,0,0,7,7,15,7,7,9,0,0,0,13,3,7,7,26,7,7,7,7,7,0,0,0,0,7,5,0,0,0,
    7,0,0,0,9,1,7,7,7,7,9,9,0,7,5,0,0,7,0,7,0,0,0,0,0,9,7,0,0,7,16,16,
    0,0,0,0,0,0,0,0,5,9,9,9,9,9,9,9,0,0,7,18,8,8,0,0,0,0,8,0,0,0,8,9,
    8,7,0,7,7,0,8,8,7,8,8,8,8,0,8,8,9,0,0,0,9,9,0,7,9,9,9,0,19,16,0,0,
    0,0,0,4,9,19,8,0,0,0,0,0,0,0,1,26,26,9,9,1,0,7,9,8,8,8,8,8,8,8,8,8,
    8,8,8,8,8,7,7,1,0,7,0,8,9,9,9,7,7,0,0,0,0,8,22,22,8,0,0,0,0,7,0,9,
    8,0,7,8,8,8,3,7,7,7,7,7,9,7,9,0,7,7,7,0,19,0,0,7,9,9,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,21,7,0,0,23,7,6,7,9,7,
    7,7,7,3,0,13,8,9,9,9,9,9,9,0,0,0,7,7,0,22,22,7,0,0,0,0,0,0,0,7,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,9,12,
};
static unsigned cx_anchor_permissions_for(unsigned type) {
    return type < 754u ? cx_anchor_masks[cx_anchor_mask_index[type]] : 0;
}
static unsigned cx_anchor_bottom_type(unsigned type) {
    return cx_anchor_permissions_for(type) & 4095u;
}
static unsigned cx_anchor_top_type(unsigned type) {
    return (cx_anchor_permissions_for(type) >> 12) & 4095u;
}
static int cx_anchor_flattens(unsigned type) {
    return (cx_anchor_permissions_for(type) & (1u << 24)) != 0;
}
#endif
